### ISSUE TITLE
Need a way to configure WavefrontJerseyFactory without files

### ISSUE THREAD

**Issue by prydin** [wavefrontHQ/wavefront-jersey-sdk-java#57]
In some environments, such as Pivotal Cloud Foundry, you don't always have easy access to OS files. We need way to configure Jersey/Wavefront programmatically instead of relying on config files. This would allow us to use e.g. config variables or beans provided by Spring to e.g. link to a proxy defined as a PCF service.

**Comment by haosong** [comment]
won't this for now.
